version: '3.8'

services:
  simplifysystem_koala:
    container_name: simplifysystem_koala
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4600:80"
    restart: unless-stopped
